Repository random-music-star/music-star-api, pull requests merged in 2025-04, with the labels that each got.

#3 feat: jwt 도입을 통한 마이그레이션
  build.gradle
  src/main/java/com/curioussong/alsongdalsong/auth/controller/AuthController.java
  src/main/java/com/curioussong/alsongdalsong/auth/dto/UserLoginRequest.java
  src/main/java/com/curioussong/alsongdalsong/auth/dto/UserLoginResponse.java
  src/main/java/com/curioussong/alsongdalsong/auth/dto/UserSignupRequest.java
  src/main/java/com/curioussong/alsongdalsong/auth/service/AuthService.java
  src/main/java/com/curioussong/alsongdalsong/config/SecurityConfig.java
  src/main/java/com/curioussong/alsongdalsong/config/StompJwtChannelInterceptor.java
  src/main/java/com/curioussong/alsongdalsong/config/WebConfig.java
  src/main/java/com/curioussong/alsongdalsong/config/WebSocketConfig.java
  src/main/java/com/curioussong/alsongdalsong/jwt/CustomUserDetailsService.java
  src/main/java/com/curioussong/alsongdalsong/jwt/JwtAuthenticationFilter.java
  src/main/java/com/curioussong/alsongdalsong/jwt/JwtTokenProvider.java
  src/main/java/com/curioussong/alsongdalsong/jwt/dto/TokenResponse.java
  src/main/java/com/curioussong/alsongdalsong/member/controller/MemberController.java
  src/main/java/com/curioussong/alsongdalsong/member/dto/GuestLogin.java
  src/main/java/com/curioussong/alsongdalsong/member/service/MemberService.java
  src/main/java/com/curioussong/alsongdalsong/room/controller/RoomController.java
  src/main/resources/application.yml
Labels: enhancement, feature, refactor

#2 feat: stomp error handler
  src/main/java/com/curioussong/alsongdalsong/channel/service/ChannelService.java
  src/main/java/com/curioussong/alsongdalsong/common/error/dto/StompErrorDetail.java
  src/main/java/com/curioussong/alsongdalsong/common/error/dto/StompErrorResponse.java
  src/main/java/com/curioussong/alsongdalsong/common/error/handler/StompExceptionHandler.java
  src/main/java/com/curioussong/alsongdalsong/common/error/stomperror/StompError.java
  src/main/java/com/curioussong/alsongdalsong/common/error/stomperror/StompException.java
  src/main/java/com/curioussong/alsongdalsong/config/StompExceptionHandler.java
  src/main/java/com/curioussong/alsongdalsong/config/WebSocketConfig.java
  src/main/java/com/curioussong/alsongdalsong/game/service/GameService.java
  src/main/java/com/curioussong/alsongdalsong/game/service/GeneralGameService.java
Labels: enhancement

#6 feat: username 반환 endpoint 구현
  src/main/java/com/curioussong/alsongdalsong/auth/controller/AuthController.java
  src/main/java/com/curioussong/alsongdalsong/auth/dto/UsernameResponse.java
Labels: feature

#7 refactor: game service 메서드 분리
  src/main/java/com/curioussong/alsongdalsong/game/service/BoardGameService.java
  src/main/java/com/curioussong/alsongdalsong/game/service/GameService.java
  src/main/java/com/curioussong/alsongdalsong/game/service/GeneralGameService.java
Labels: refactor

#8 fix: 채널 내 멤버 목록 조회 DTO 형태 변경
  src/main/java/com/curioussong/alsongdalsong/member/controller/MemberController.java
  src/main/java/com/curioussong/alsongdalsong/member/dto/MemberStatus.java
  src/main/java/com/curioussong/alsongdalsong/member/dto/MemberStatusDTO.java
  src/main/java/com/curioussong/alsongdalsong/member/service/MemberService.java
Labels: fix

#9 fix: 소켓 통신 토큰 관리
  src/main/java/com/curioussong/alsongdalsong/config/SecurityConfig.java
  src/main/java/com/curioussong/alsongdalsong/config/StompChannelInterceptor.java
  src/main/java/com/curioussong/alsongdalsong/config/StompJwtChannelInterceptor.java
  src/main/java/com/curioussong/alsongdalsong/config/WebSocketConfig.java
Labels: fix
